# The Docker image that will be used to build your app
image: python:3.10

# Functions that should be executed before the build script is run
before_script:
  - pip install -U sphinx
  - pip install sphinx-rtd-theme
  - pip install -r requirements.txt
  - wget https://s3-eu-west-1.amazonaws.com/download.agisoft.com/Metashape-2.1.2-cp37.cp38.cp39.cp310.cp311-abi3-linux_x86_64.whl
  - pip install Metashape-2.1.2-cp37.cp38.cp39.cp310.cp311-abi3-linux_x86_64.whl

pages:
  script:
    - sphinx-apidoc -e -E -o docs .
    - sphinx-build -b html docs public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
