values:
  default_sfm: 'micmac'
  default_cloud_processor: 'cloudcompare'
  default_detector: 'detection_cctag'
  default_scalebars_conf: '%root%/Configuration/scaleBar.csv'

tools:
  # SFM
  micmac:
    class: Grounded.Tools.SFM.MicMac.MicMac
    arguments:
      path_mm3d: '/opt/micmac/bin/mm3d'
      distorsion_model: 'FraserBasic'
      zoom_final: 'QuickMac'
      tapioca_mode: 'All'
      tapioca_resolution: '1000'
      tapioca_second_resolution: '1000'

  metashape:
    class: Grounded.Tools.SFM.Metashape.Metashape
    arguments:
      downscale: '8'

  # PointCloudProcessor
  cloudcompare:
    class: Grounded.Tools.PointCloudProcessor.CloudCompare.CloudCompare
    arguments:
      path_cloud_compare: 'cloudcompare.CloudCompare'
      version: '2.11.1'

  # DetecteurMire
  detection_cctag:
    class: Grounded.Tools.DetecteurMire.DetectionCCTag.DetectionCCTag
    arguments:
      path_cctag_directory: '/opt/CCTag/'

  detection_metashape:
    class: Grounded.Tools.DetecteurMire.DetectionMetashape.DetectionMetashape