values:
  default_sfm: 'micmac'
  default_cloud_processor: 'cloudcompare'
  default_detector: 'detection_cctag'
  default_scalebars_conf: '%root%/Configuration/scaleBar.csv'
  default_outdir_name: 'out'

tools:
  # SFM
  micmac:
    class: Grounded.Tools.SFM.MicMac.MicMac
    arguments:
      path_mm3d: '/opt/micmac/bin/mm3d'
      working_directory: 'micmac_working_directory'
      output_dir: '%default_outdir_name%'
      distorsion_model: 'FraserBasic'
      zoom_final: 'QuickMac'
      tapioca_mode: 'All'
      tapioca_resolution: '1000'
      tapioca_second_resolution: '1000'
      reuse_wd: 'False'

  metashape:
    class: Grounded.Tools.SFM.Metashape.Metashape
    arguments:
      working_directory: 'metashape_working_directory'
      output_dir: '%default_outdir_name%'
      downscale: '8'

  # PointCloudProcessor
  cloudcompare:
    class: Grounded.Tools.PointCloudProcessor.CloudCompare.CloudCompare
    arguments:
      path_cloud_compare: 'cloudcompare.CloudCompare'
      working_directory: 'cloudCompare_working_directory'
      output_dir: '%default_outdir_name%'

  # DetecteurMire
  detection_cctag:
    class: Grounded.Tools.DetecteurMire.DetectionCCTag.DetectionCCTag
    arguments:
      path_cctag_directory: '/opt/CCTag/'
      working_directory: 'cctag_working_directory'
      output_dir: '%default_outdir_name%'

  detection_metashape:
    class: Grounded.Tools.DetecteurMire.DetectionMetashape.DetectionMetashape
    arguments:
      working_directory: 'detectionMetashape_working_directory'
      output_dir: '%default_outdir_name%'
